import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faShareNodes} from '@fortawesome/free-solid-svg-icons'
import { faCommentDots} from '@fortawesome/free-solid-svg-icons'
import { faHandHolding} from '@fortawesome/free-solid-svg-icons'
import Image from 'next/image';
import ClientsLogo from '../components/clientslogo';

// export const metadata = { 
//   title: "Title",
//   description: "Generated by create next app",
// };

// app/about/page.js
export async function generateMetadata() {
  const url = 'https://49poundsocial.com/about-us'; // this must match the real WordPress page URL

  try {
    const res = await fetch(
      `https://49poundsocial.com/wp-json/rankmath/v1/getHead?url=${encodeURIComponent(url)}`,
      { cache: 'no-store' }
    );
    const data = await res.json();

    if (data.success) {
      const html = data.head;

      const titleMatch = html.match(/<title>(.*?)<\/title>/);
      const descMatch = html.match(/<meta name="description" content="(.*?)"/);

      return {
        title: titleMatch?.[1] || 'Fallback Title',
        description: descMatch?.[1] || 'Fallback description',
      };
    } else {
      console.warn('Rank Math API response failed:', data);
    }
  } catch (e) {
    console.error('RankMath SEO fetch error:', e);
  }

  return {
    title: 'Fallback Title',
    description: 'Fallback description',
  };
}


function about() {
  return (
    <>
   {/* start section 1 */}
<section className='grid grid-cols-1 md:grid-cols-2 gap-9 items-center bg-backgroundcolor px-6 md:px-16 lg:px-28 py-10 md:h-[537px] font-figtree '>
  <div className='flex flex-col justify-center items-start'>
    <h1 className='text-white font-[700] text-[40px] sm:text-[50px] md:text-[65px] leading-tight capitalize'>
      An Award-Winning
    </h1>
    <h3 className='text-secondarycolor font-[500] text-[24px] sm:text-[30px] md:text-[37px] leading-snug capitalize'>
      social media management agency
    </h3>
    <div className="flex flex-row lg:flex-row gap-4 pt-6 sm:pt-4 lg:pr-60">
      <button className="bg-secondarycolor text-backgroundcolor w-[155px] h-[46px] font-bold text-[13px] rounded-[6px] uppercase">
        book a call
      </button>
      <button className="bg-white text-backgroundcolor w-[155px] h-[46px] font-bold text-[13px] rounded-[6px] uppercase">
        get started
      </button>
    </div>
  </div>
   <div className='hidden md:flex justify-center items-center md:pl-24 mt-10 md:mt-0'>
<Image 
  src="/about/Black-Grey-Minimal-Color-Branding-Inclusive-Skincare-Instagram-Post-400-x-400-px-2.png" 
  alt="Home Hero 1" 
  width={467} 
  height={367} // or whatever actual height you'd like
  className="rounded-[12px] w-full max-w-[400px]"
/>
</div>
</section>
{/* end section 1 */}



   {/* start section 2 */}
<section className='grid grid-cols-1 xl:grid-cols-2  xl:grid-rows-1 md:grid-rows-2 gap-10 px-6 md:px-16 xl:px-48 py-10 bg-white text-black capitalize font-figtree'>
  <div className='flex justify-center items-center'>
  
<Image 
  src="/about/image-11.png" 
  alt="Home Hero 1" 
  width={570} 
  height={372} // or whatever actual height you'd like
  className='w-[400px] h-[200px] xl:w-[570px] md:w-[949px] md:h-[350px] xl:h-auto rounded-[12px]' 
/>

  </div>
  <div className='flex flex-col justify-center'>
    <h2 className='text-[28px] sm:text-[32px] md:text-[36px] font-[700]'>about us</h2>
    <p className='text-[15px] sm:text-[16px] normal-case pt-4 font-albert'>
      Welcome to 49 Pound Social, your go-to social media management company based in London. Founded in 2022, we are dedicated to providing affordable, high-quality social media services tailored for SMEs across the UK and beyond.
    </p>
    <p className='text-[15px] sm:text-[16px] normal-case pt-4 font-albert'>
      At 49 Pound Social, we offer a comprehensive range of services including social media management, professional SEO blog articles, branding, and social media marketing. Our team of 10 young, creative individuals is passionate about social media and committed to delivering exceptional results. Each team member brings a unique set of skills, allowing us to craft compelling content and effective social media strategies that resonate with your target audience.
    </p>
  </div>
</section>
{/* end section 2 */}


    {/* start section 3 */}
<section className='grid grid-cols-1 md:grid-rows-2 xl:grid-rows-1 xl:grid-cols-2 gap-10 px-6 md:px-16 xl:px-48 py-10 bg-backgroundcolor text-white capitalize font-figtree'>
  <div className='flex flex-col justify-center'>
    <h2 className='text-[28px] sm:text-[32px] md:text-[36px] font-[700]'>
      What Sets Us Apart?
    </h2>
    <p className='text-[15px] sm:text-[16px] normal-case pt-4 w-full  xl:w-[497px] font-albert'>
      What truly sets 49 Pound Social apart is our unwavering commitment to quality and affordability. We understand that not all cheap social media management services are created equal. Some may offer low prices but compromise on the quality of posts and engagement. That&apos;s not the case with us. We focus on delivering high-quality visuals and branded content, ensuring that every post tells your brand&apos;s story and engages your audience meaningfully.
    </p>
    <p className='text-[15px] sm:text-[16px] normal-case pt-4 w-full xl:w-[497px] font-albert'>
      Additionally, we pride ourselves on providing unmatched value for money. Our services are designed to offer more for less, and we guarantee to beat any competitor&apos;s price. This commitment to affordability and quality has enabled us to create over 10,000 posts to date, helping numerous clients build their online presence and connect with their customers effectively.
    </p>
  </div>
  <div className='flex justify-center items-center'>
   
<Image 
  src="/about/smiley-face.webp" 
  alt="Home Hero 1" 
  width={570} 
  height={521} // or whatever actual height you'd like
      className='w-[400px] h-[200px] md:w-[949px] md:h-[350px] xl:w-[570px] xl:h-[521px] rounded-[12px] object-cover' 
/>


  </div>
</section>
{/* end section 3 */}


       {/* start section 4 */}
<section className='flex flex-col justify-center items-center text-black capitalize py-12 px-4 md:px-8 lg:px-16 bg-white font-figtree'>
  <h2 className='text-[32px] sm:text-[38px] md:text-[45px] font-[800] text-center'>our services.</h2>

  {/* Top 3 cards */}
  <div className='flex flex-col xl:flex-row gap-5 pt-6 items-center'>
    <div className='flex flex-col justify-center items-center w-[400px] md:w-[949px] xl:w-[364px] h-[314px] text-backgroundcolor bg-boxbackground border border-black rounded-[8px]'>
      <FontAwesomeIcon icon={faShareNodes} className='w-[90px] h-[90px]' />
      <span className='text-[22px] font-[600] w-[156px] pt-4 uppercase leading-none text-center'>socal media management</span>
      <p className='text-[16px] px-7 pt-2 text-center normal-case text-black font-albert'>
        We&apos;ve got your social sorted! Our team will take care of your social media, so you can focus on what you do best-running your business.
      </p>
    </div>
    <div className='flex flex-col justify-center items-center w-[400px] md:w-[949px] xl:w-[364px] h-[314px] text-backgroundcolor bg-boxbackground border border-black rounded-[8px]'>
      <FontAwesomeIcon icon={faShareNodes} className='w-[90px] h-[90px]' />
      <span className='text-[22px] font-[600] w-[156px] pt-4 uppercase leading-none text-center'>SOCIAL <br />MEDIA ADS</span>
      <p className='text-[16px] px-7 pt-2 text-center normal-case text-black font-albert'>
        Boost your brand with our social media ads! We&apos;ll craft eye-catching campaigns to put your business in the spotlight.
      </p>
    </div>
    <div className='flex flex-col justify-center items-center w-[400px] md:w-[949px] xl:w-[364px] h-[314px] text-backgroundcolor bg-boxbackground border border-black rounded-[8px]'>
      <FontAwesomeIcon icon={faCommentDots} className='w-[90px] h-[90px]' />
      <span className='text-[22px] font-[600] w-[156px] pt-4 uppercase leading-none text-center'>SEO <br />BLOGS</span>
      <p className='text-[16px] px-7 pt-2 text-center normal-case text-black font-albert'>
        Our SEO blogs are like the crown jewels of content. Informative, engaging, and Googles best friend-they&apos;ll keep your audience coming back for more.
      </p>
    </div>
  </div>

  {/* Bottom 2 cards */}
  <div className='flex flex-col lg:flex-row gap-5 pt-6 items-center'>
    <div className='flex flex-col justify-center items-center w-[400px] xl:w-[558px] md:w-[465px] h-[263px] text-backgroundcolor bg-boxbackground border border-black rounded-[8px]'>
      <FontAwesomeIcon icon={faShareNodes} className='w-[90px] h-[90px]' />
      <span className='text-[22px] font-[600] w-[156px] pt-4 uppercase leading-none text-center'>Branding</span>
      <p className='text-[16px] px-7 pt-2 text-center normal-case text-black font-albert'>
        Branding is really important for making your business successful. It&apos;s not just about having a logo. It&apos;s about what your business stands for.
      </p>
    </div>
    <div className='flex flex-col justify-center items-center  w-[400px] xl:w-[558px] md:w-[465px]  h-[263px] text-backgroundcolor bg-boxbackground border border-black rounded-[8px]'>
      <FontAwesomeIcon icon={faHandHolding} className='w-[90px] h-[90px]' />
      <span className='text-[22px] font-[600] w-[156px] pt-4 uppercase leading-none text-center'>Reselller</span>
      <p className='text-[16px] px-7 pt-2 text-center normal-case text-black font-albert'>
        Boost your brand with our social media ads! We&apos;ll craft eye-catching campaigns to put your business in the spotlight.
      </p>
    </div>
  </div>

  {/* Button */}
  <div className='flex justify-center items-center text-[24px] sm:text-[30px] md:text-[37px] w-full max-w-[335px] h-[56px] bg-secondarycolor text-backgroundcolor rounded-[10px] mt-10'>
    for small business
  </div>
</section>
{/* end section 4 */}



        {/* start section 5 */}

         <ClientsLogo />

    {/* end section 5 */}


      {/* start section 6 */}
      
<section className="flex flex-col md:flex-row justify-center items-center relative gap-9 py-12 px-4 bg-white h-auto font-figtree">
  {/* Left Card */}
  <div className="flex flex-col justify-center w-full max-w-[500px] h-auto bg-backgroundcolor text-white rounded-[15px] py-8">
    <div className="flex justify-center">
      {/* <img src="/images/img8.webp" alt="Logo" className="h-[63px] w-[158px] object-contain" /> */}

<Image 
  src="/about/49-pound-White-orange-1-e1705293574283.webp" 
  alt="Home Hero 1" 
  width={158} 
  height={63} // or whatever actual height you'd like
className="h-[63px] w-[158px] object-contain"/>

    </div>

    <span className="text-[18px] pt-9 px-6 md:px-12 font-[600]">More value for you money!</span>
    <p className="px-6 md:px-12 text-[16px] pt-1 font-albert">You get loads without spending loads. Top service, no hidden extras, and everything you need thrown in. It&apos;s a no-brainer.</p>
    
    <span className="pt-9 px-6 md:px-12 text-[18px] font-[600]">Branded Graphics Included as Standard!</span>
    <p className="px-6 md:px-12 text-[16px] pt-1 font-albert">Fancy graphics? Included. We don&apos;t do add-ons for stuff you actually need. It&apos;s all in the mix from the get-go.</p>
    
    <span className="pt-9 px-6 md:px-12 text-[18px] font-[600]">Unlimited Revisions?</span>
    <p className="px-6 md:px-12 text-[16px] pt-1 font-albert">Oh, absolutely! We&apos;re fully committed to your satisfaction and ensuring that every detail is just right. Your input and feedback are invaluable to us.</p>
  </div>

<div className="hidden xl:flex absolute z-30 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
  {/* <img src="/images/img9.webp" alt="Logo" className="h-[66px] w-[66px] object-contain rounded-full" /> */}

<Image 
  src="/about/unnamed-1-e1704792601962.png" 
  alt="Home Hero 1" 
  width={66} 
  height={66} 
className="h-[66px] w-[66px] object-contain rounded-full" />
</div>


  {/* Right Card */}
  <div className="flex flex-col justify-center w-full max-w-[500px] h-auto bg-white text-black rounded-[15px] border border-black py-11">
    <div className="flex justify-center text-[36px] md:text-[56px] font-[700] capitalize px-6 text-center">
      other agencies
    </div>

    <span className="text-[18px] pt-9 px-6 md:px-12 font-[600]">Expensive</span>
    <p className="px-6 md:px-12 text-[16px] pt-1 font-albert">They might make you pay more for what we give you straight up. Expect extra charges for the basics.</p>
    
    <span className="pt-9 px-6 md:px-12 text-[18px] font-[600]">Charge For Adding Logo or Branding</span>
    <p className="px-6 md:px-12 text-[16px] pt-1 font-albert">Want graphics? That&apos;ll be extra. It&apos;s like ordering a burger and paying extra for the bun.</p>
    
    <span className="pt-9 px-6 md:px-12 text-[18px] font-[600]">Hidden Extras</span>
    <p className="px-6 md:px-12 text-[16px] pt-1 font-albert">On the flip side, they may restrict the number of revisions you&apos;re allowed, and they might even charge extra for additional changes.</p>
  </div>
</section>
{/* end section 6 */}


      {/* start section 7 */}
<section className='grid grid-cols-1 md:grid-cols-2 h-auto md:h-[400px] bg-secondarycolor text-backgroundcolor font-figtree'>
  <div className='flex items-center justify-center md:justify-end px-6 md:pl-40 text-center md:text-start py-8 md:py-0'>
    <h2 className='w-full md:w-[545px] text-2xl md:text-[44px] font-[500] capitalize leading-snug md:leading-[50px]'>
      Monthly Packages That Are Cheaper than Your Daily Cappuccino!
    </h2>
  </div>
  <div className='flex justify-center items-center pb-8 md:pb-0'>
    <Image 
  src="/about/cappuccino-with-number-49.png" 
  alt="Home Hero 1" 
  width={263} 
  height={544}
      className='h-[180px] w-[200px] md:h-[219px] md:w-[241px] object-contain' 
/>
  </div>
</section>
{/* end section 7 */}


    </>
  )
}

export default about