import './index.css';
import Header from './components/header';
import Footer from './components/footer';

// export const metadata = {
//   title: "Title",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
       <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Albert+Sans:ital,wght@0,100..900;1,100..900&family=Figtree:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header/>
        {children}
         <Footer/>

      </body>
    </html>
  );
}
