import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheck} from '@fortawesome/free-solid-svg-icons'
import { faCircleCheck} from '@fortawesome/free-solid-svg-icons'
import { faCircleXmark} from '@fortawesome/free-solid-svg-icons'
import SampleSection from "./components/sample-section";
import Image from 'next/image';

// export const metadata = {
//   title: "Title",
//   description: "Generated by create next app",
// };
export async function generateMetadata() {
  const url = 'https://49poundsocial.com/'; // Make sure this matches the actual page

  try {
    const res = await fetch(
      `https://49poundsocial.com/wp-json/rankmath/v1/getHead?url=${encodeURIComponent(url)}`,
      { cache: 'no-store' }
    );
    const data = await res.json();

    if (data.success) {
      const html = data.head;

      const titleMatch = html.match(/<title>(.*?)<\/title>/);
      const descMatch = html.match(/<meta name="description" content="(.*?)"/);

      return {
        title: titleMatch?.[1] || 'Fallback Title',
        description: descMatch?.[1] || 'Fallback description',
      };
    } else {
      console.warn('Rank Math API response failed:', data);
    }
  } catch (e) {
    console.error('RankMath SEO fetch error:', e);
  }

  return {
    title: 'Fallback Title',
    description: 'Fallback description',
  };
}


export default function Home() {

  return (
    <>
     {/* start home page section 1 */}
<section className="grid grid-cols-1 md:grid-cols-2 bg-backgroundcolor h-auto md:h-[656px] font-figtree">
  <div className="flex flex-col justify-center px-6 md:pl-28 py-10 md:py-0 text-center md:text-left">
    <h1 className="text-[50px] sm:text-[60px] md:text-[50px] xl:text-[87px] text-white capitalize font-semibold max-w-full md:w-[612px] leading-tight md:leading-none">
      Affordable social media management.
    </h1>
    <p className="text-secondarycolor text-[24px] sm:text-[32px] md:text-[40px] font-[700] pt-4">
      Just £49/pm
    </p> 
    <div className="flex flex-row sm:flex-row gap-4 sm:gap-5 pt-4 justify-center md:justify-start">
      <button className="bg-secondarycolor text-backgroundcolor w-full sm:w-[155px] h-[46px] font-bold text-[13px] rounded-[6px] uppercase">book a call</button>
      <button className="bg-white text-backgroundcolor w-full sm:w-[155px] h-[46px] font-bold text-[13px] rounded-[6px] uppercase"> get started</button>
    </div>
    <div className="flex flex-col xl:flex-row gap-4 xl:gap-9 text-white text-[15px] sm:text-[17px] pt-5 font-albert">
      <div className='flex gap-2 justify-center md:justify-start items-center'>
        <FontAwesomeIcon icon={faCheck} className='w-[16px] h-[16px] text-secondarycolor' />
        <p>No contracts. Cancel anytime</p>
      </div>
      <div className='flex gap-2 justify-center md:justify-start items-center'>
        <FontAwesomeIcon icon={faCheck} className='w-[16px] h-[16px] text-secondarycolor' />
        <p>14-day money-back guarantee</p>
      </div>
    </div>
  </div>
  <div className="flex justify-center items-center px-6 md:px-0 py-6 md:py-0">
          <Image 
  src="/home/social-media-creative-posts.webp" 
  alt="Home Hero 1" 
  width={420} 
  height={300} // or whatever actual height you'd like
  className="md:w-[350px] lg:w-[400px] xl:w-[420px] h-auto"
/>


  </div>
</section>
{/* end home page section 1 */}



              {/* start home page section 2 */}
<section className="w-full grid grid-cols-1 md:grid-cols-2 bg-white h-auto xl:h-[600px] capitalize text-black gap-10 md:gap-0 py-10 xl:py-0 font-figtree">
  <div className="flex justify-center items-center order-2 md:order-1">
    <Image
      src="/home/Untitled-design-2025-01-07T094330.615.webp"
      alt=""
      width={1000}
      height={500}
      className="rounded-r-[20px] max-w-full h-auto"
    />
  </div>
  <div className="flex flex-col justify-center md:pr-14 text-center md:text-left order-1 md:order-2 px-6 md:px-14">
    <div className='flex gap-3'>
      <div className="w-[2px] h-30 bg-secondarycolor"></div>
       <h2 className="text-[28px] sm:text-[32px] md:text-[30px]  xl:text-[45px] font-[700] leading-snug md:leading-none max-w-full md:w-[656px]">
      Affordable social media marketing for small businesses
    </h2>
    </div>
   
    <p className="text-[15px] sm:text-[16px] pt-5 font-albert">
      Social media matters—but who has the time? We get it. That&apos;s why our affordable social media marketing service gives small businesses the helping hand they need. Reliable, stress-free support so you can stop juggling posts and start focusing on what you do best with affordable social media marketing that works.
    </p>
  </div>
</section>

{/* end home page section 2 */}


                      {/* start home page section 3 */}
<section className="grid grid-cols-1 md:grid-cols-2 bg-backgroundcolor h-auto xl:h-[600px] capitalize text-white gap-10 md:gap-14 px-6 md:px-0 py-10 xl:py-0 font-figtree ">
  <div className="flex flex-col justify-center md:pl-16 text-center md:text-left">
     <div className='flex gap-3'>
      <div className="w-[2px] h-30 bg-secondarycolor"></div>
     <h2 className="text-[28px] sm:text-[32px] md:text-[36px] font-[700] leading-snug md:leading-none max-w-full md:w-[656px]">
      Scroll-Stopping Visuals that catch the eye.
    </h2>
    </div>
 
    <p className="text-[15px] sm:text-[16px] pt-5 max-w-full md:w-[695px] font-albert">
      We focus on crafting content that grabs attention and keeps your audience engaged. From bold social media posts to clever carousels, lighthearted memes, and fun puzzle-style content — every visual we create is designed to reflect your brand and connect with your audience. Our in-house creative team puts care into every post, so you can stand out online without the stress.
    </p>
  </div>
  <div className="flex justify-center items-center">
    <Image
  src="/home/Untitled-design-2025-01-07T094317.915.webp"
  alt=""
  width={1000} 
  height={500}
  className="rounded-l-[20px] max-w-full h-auto"
/>
  </div>
</section>
{/* end home page section 3 */}



{/* start home page section 4 */}
<section className="grid grid-cols-1 md:grid-cols-2 bg-white h-auto xl:h-[600px] capitalize text-black gap-10 md:gap-14 px-6 md:px-0 py-10 xl:py-0 font-figtree">
  <div className="flex justify-center items-center order-2 md:order-1">
    {/* <img src="/images/img4.webp" alt="" className="rounded-r-[20px] max-w-full h-auto" /> */}
 <Image
  src="/home/Untitled-design-2025-01-07T094303.700.webp"
  alt=""
  width={1000} 
  height={500}
  className="rounded-r-[20px] max-w-full h-auto"
/>

  </div>
  <div className="flex flex-col justify-center md:pr-14 text-center md:text-left order-1 md:order-2">
   <div className='flex gap-3'>
      <div className="w-[2px] h-30 bg-secondarycolor"></div>
      <h2 className="text-[28px] sm:text-[32px] md:text-[36px] xl:text-[43px] font-[700] leading-snug md:leading-none max-w-full md:w-[656px]">
      Posts Scheduled & Managed Efficiently
    </h2>
    </div>
    <p className="text-[15px] sm:text-[16px] pt-5 font-albert">
      Once you&apos;ve approved the content, we&apos;ll ensure it&apos;s posted to your social channels according to the agreed schedule, always punctually. Preview your upcoming posts with ease, as we&apos;ve got the timing down to a science. We analyse follower activity to determine the best content and optimal posting times for your accounts.
    </p>
  </div>
</section>
{/* end home page section 4 */}




                                                {/* start home page section 5*/}

<section className="flex flex-col items-center capitalize min-h-[1192px] bg-backgroundcolor px-4 sm:px-6 md:px-10 py-10 font-figtree">
  <h2 className="text-white font-bold text-[28px] sm:text-[32px] md:text-[36px] pt-6 text-center">ourplans.</h2>
  <h4 className="text-white text-[18px] sm:text-[20px] md:text-[22px] font-[600] pt-4 text-center">FREE Trial On Affordable Plan-Try Before You Buy!</h4>
  <h5 className="text-white text-[16px] sm:text-[17px] md:text-[18px] w-full max-w-[912px] text-center pt-4">
    Why not experience the difference risk-free? No credit card required—just one month of great content, totally free!
  </h5>
  <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 pt-9">

{/* first card */}

<div className=" flex flex-col items-center w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl  h-auto  bg-white rounded-[20px] text-backgroundcolor px-10 py-10">
  <h3 className="text-[48px] md:text-[40px] xl:text-[48px] font-[700] pt-3 ">affordable</h3>
  <h4 className='text-[30px] md:text-[20px] xl:text-[30px] font-[600]'>£49/month</h4>
  <p className="text-sm font-semibold pt-1 font-albert">for startup on a tight budget</p>


  <div className='flex flex-col place-content-start font-albert'> 
 
  <div className='flex gap-3 items-center pt-5 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>Choose your favourite 
            </p>
            </div>

            <div className='flex gap-3 items-center  pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>2 eye-catching posts p/w
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3  '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>High-quality visuals
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3'>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>Professional captions
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3'>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>Scheduling & posting
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>UK-based Content
            </p>
            </div>
             <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>UK-based Content
            </p>
            </div>
             <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>UK-based Content
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3'>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>Monthly Rolling Plan
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3'>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>Email Support
            </p>
            </div>
            
  </div>
<div className='flex  justify-center items-center pt-6  '>
<button className=' mt-auto text-[13px] bg-secondarycolor text-backgroundcolor uppercase font-semibold w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl h-[46px] rounded-[6px] px-20'>sign up now</button>

</div>

</div>

{/* second card */}


<div className=" flex flex-col items-center h-auto w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl  bg-secondarycolor text-backgroundcolor border border-s-white rounded-[20px] px-10 py-10">
<h3 className="text-[48px]  md:text-[40px] xl:text-[48px] font-[700] pt-3 ">value</h3>
  <h4 className='text-[30px] md:text-[20px] xl:text-[30px] font-[600]'>£99/month</h4>
  <p className="text-sm font-semibold text-white pt-1 font-albert ">great for small businesses</p>

  <div className='flex flex-col place-content-start font-albert'> 
 
  <div className='flex gap-3 items-center pt-5 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>hight-quality visuals
            </p>
            </div>

            <div className='flex gap-3 items-center  pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>5 posts per week
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3  '>
            <FontAwesomeIcon icon={ faCircleXmark} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>Linkedin Newsletter
            </p>
            </div>
           
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>2 eye-catching posts p/w
            </p>
            </div>
           
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={ faCircleXmark} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>pinterest
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={ faCircleXmark} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>group posting
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>uk-based content 
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>uk-based content 
            </p>
            </div>
           <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>uk-based content 
            </p>
            </div>
           
           
             <div className='flex gap-3 items-center pt-3'>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-backgroundcolor' />
            <p>email support
            </p>
            </div>
            
  </div>

<div className='flex  justify-center items-center pt-6 '>
<button className=' mt-auto text-[13px] uppercase bg-backgroundcolor text-white font-semibold w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl h-[46px] rounded-[6px] px-20'>sign up now</button>
</div>

</div>

{/* third card */}

<div className=" flex flex-col items-center h-auto w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl  bg-backgroundcolor border text-white border-s-white rounded-[20px] px-10 py-10">
<h3 className="text-[48px] md:text-[40px] xl:text-[48px] font-[700] pt-3">ultimate</h3>
  <h4 className='text-[30px] md:text-[20px] xl:text-[30px] font-[600]'>£159/month</h4>
  <p className="text-sm font-semibold text-white pt-1 font-albert">more graphics and content</p>

  <div className='flex flex-col place-content-start font-albert'> 
 
  <div className='flex gap-3 items-center pt-5 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>High-quality visuals
            </p>
            </div>

            <div className='flex gap-3 items-center  pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>7 Posts per week
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3'>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>1 Linkedin Newsletter
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>Captions & hashtags
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>Scheduling & posting
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>facebook
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>2 eye-catching posts p/w
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>Linkedin or twitter
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3 '>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>pinterest
            </p>
            </div>
            <div className='flex gap-3 items-center pt-3'>
            <FontAwesomeIcon icon={faCircleCheck} className='w-[16px] h-[16px] text-white' />
            <p>group posting
            </p>
            </div>
           
</div>

<div className='flex  justify-center items-center pt-6'>
<button className=' mt-auto text-[13px] uppercase bg-white text-backgroundcolor font-semibold w-full sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl h-[46px] rounded-[6px] px-20'>sign up now</button>
</div>

</div>
</div>
</section>

                                                {/* end home page section 5 */}

            {/* start home page section 6 */}

               <SampleSection />
            {/* end home page section 6 */}


    </>
  );
}

